Traceback (most recent call last):
  File "C:\Users\DeLL\Documents\masterIA S1\Intro IA\min_porject\script\entrai_eval.py", line 148, in <module>
    svm_model, vectorizer =  train_and_evaluate_svm(df, model_path)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DeLL\Documents\masterIA S1\Intro IA\min_porject\script\entrai_eval.py", line 58, in train_and_evaluate_svm
    X_train_vec = vectorizer.fit_transform(X_train)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DeLL\Documents\masterIA S1\Intro IA\min_porject\myenv\Lib\site-packages\sklearn\feature_extraction\text.py", line 2104, in fit_transform
    X = super().fit_transform(raw_documents)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DeLL\Documents\masterIA S1\Intro IA\min_porject\myenv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Users\DeLL\Documents\masterIA S1\Intro IA\min_porject\myenv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\DeLL\Documents\masterIA S1\Intro IA\min_porject\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'ngram_range' parameter of TfidfVectorizer must be an instance of 'tuple'. Got [1, 2] instead.
